export const weatherData = {
    "latitude": 29.427839,
    "longitude": -98.494636,
    "timezone": "America/Chicago",
    "currently": {
        "time": 1550985515,
        "summary": "Clear",
        "icon": "clear-night",
        "nearestStormDistance": 74,
        "nearestStormBearing": 88,
        "precipIntensity": 0,
        "precipProbability": 0,
        "temperature": 57.88,
        "apparentTemperature": 57.88,
        "dewPoint": 25.62,
        "humidity": 0.29,
        "pressure": 1019.76,
        "windSpeed": 3.98,
        "windGust": 9.94,
        "windBearing": 318,
        "cloudCover": 0.02,
        "uvIndex": 0,
        "visibility": 9.71,
        "ozone": 266.7
    },
    "minutely": {
        "summary": "Clear for the hour.",
        "icon": "clear-night",
        "data": [
            {
                "time": 1550985480,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550985540,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550985600,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550985660,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550985720,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550985780,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550985840,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550985900,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550985960,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550986020,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550986080,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550986140,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550986200,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550986260,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550986320,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550986380,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550986440,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550986500,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550986560,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550986620,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550986680,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550986740,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550986800,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550986860,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550986920,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550986980,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550987040,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550987100,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550987160,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550987220,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550987280,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550987340,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550987400,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550987460,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550987520,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550987580,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550987640,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550987700,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550987760,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550987820,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550987880,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550987940,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550988000,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550988060,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550988120,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550988180,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550988240,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550988300,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550988360,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550988420,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550988480,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550988540,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550988600,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550988660,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550988720,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550988780,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550988840,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550988900,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550988960,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550989020,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1550989080,
                "precipIntensity": 0,
                "precipProbability": 0
            }
        ]
    },
    "hourly": {
        "summary": "Partly cloudy starting tomorrow evening.",
        "icon": "partly-cloudy-night",
        "data": [
            {
                "time": 1550984400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 58.36,
                "apparentTemperature": 58.36,
                "dewPoint": 26.17,
                "humidity": 0.29,
                "pressure": 1019.52,
                "windSpeed": 3.72,
                "windGust": 9.41,
                "windBearing": 313,
                "cloudCover": 0.01,
                "uvIndex": 0,
                "visibility": 9.57,
                "ozone": 266.61
            },
            {
                "time": 1550988000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 56.79,
                "apparentTemperature": 56.79,
                "dewPoint": 24.38,
                "humidity": 0.28,
                "pressure": 1020.28,
                "windSpeed": 4.64,
                "windGust": 11.13,
                "windBearing": 325,
                "cloudCover": 0.03,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 266.91
            },
            {
                "time": 1550991600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 55.14,
                "apparentTemperature": 55.14,
                "dewPoint": 21.98,
                "humidity": 0.27,
                "pressure": 1021.12,
                "windSpeed": 7.49,
                "windGust": 16.72,
                "windBearing": 339,
                "cloudCover": 0.09,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 266.57
            },
            {
                "time": 1550995200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0.0018,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 53.75,
                "apparentTemperature": 53.75,
                "dewPoint": 21.52,
                "humidity": 0.28,
                "pressure": 1022.1,
                "windSpeed": 9.88,
                "windGust": 21.98,
                "windBearing": 357,
                "cloudCover": 0.11,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 265.77
            },
            {
                "time": 1550998800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 52.05,
                "apparentTemperature": 52.05,
                "dewPoint": 23.59,
                "humidity": 0.33,
                "pressure": 1022.76,
                "windSpeed": 10.62,
                "windGust": 24.3,
                "windBearing": 12,
                "cloudCover": 0.09,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 264.97
            },
            {
                "time": 1551002400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 49.85,
                "apparentTemperature": 45.73,
                "dewPoint": 25.62,
                "humidity": 0.39,
                "pressure": 1023.41,
                "windSpeed": 10.36,
                "windGust": 24.04,
                "windBearing": 17,
                "cloudCover": 0.08,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 264.18
            },
            {
                "time": 1551006000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 47.32,
                "apparentTemperature": 42.88,
                "dewPoint": 27.04,
                "humidity": 0.45,
                "pressure": 1023.94,
                "windSpeed": 9.55,
                "windGust": 22.63,
                "windBearing": 18,
                "cloudCover": 0.07,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 263.42
            },
            {
                "time": 1551009600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0.0013,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 45.63,
                "apparentTemperature": 40.99,
                "dewPoint": 27.83,
                "humidity": 0.5,
                "pressure": 1024.88,
                "windSpeed": 9.06,
                "windGust": 21.48,
                "windBearing": 20,
                "cloudCover": 0.05,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 263
            },
            {
                "time": 1551013200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0.0014,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 44.92,
                "apparentTemperature": 40.13,
                "dewPoint": 27.94,
                "humidity": 0.51,
                "pressure": 1026.05,
                "windSpeed": 9.05,
                "windGust": 20.49,
                "windBearing": 24,
                "cloudCover": 0.03,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 262.98
            },
            {
                "time": 1551016800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 46.05,
                "apparentTemperature": 41.28,
                "dewPoint": 27.76,
                "humidity": 0.49,
                "pressure": 1027.34,
                "windSpeed": 9.64,
                "windGust": 20.99,
                "windBearing": 28,
                "cloudCover": 0.01,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 263.22
            },
            {
                "time": 1551020400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0012,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 48.75,
                "apparentTemperature": 43.9,
                "dewPoint": 27.19,
                "humidity": 0.43,
                "pressure": 1028.28,
                "windSpeed": 11.84,
                "windGust": 26.56,
                "windBearing": 34,
                "cloudCover": 0,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 263.8
            },
            {
                "time": 1551024000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0011,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 52.05,
                "apparentTemperature": 52.05,
                "dewPoint": 26.8,
                "humidity": 0.37,
                "pressure": 1028.58,
                "windSpeed": 11.64,
                "windGust": 22.72,
                "windBearing": 43,
                "cloudCover": 0,
                "uvIndex": 4,
                "visibility": 10,
                "ozone": 264.63
            },
            {
                "time": 1551027600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0009,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 55.98,
                "apparentTemperature": 55.98,
                "dewPoint": 26.61,
                "humidity": 0.32,
                "pressure": 1028.52,
                "windSpeed": 11.27,
                "windGust": 18.8,
                "windBearing": 49,
                "cloudCover": 0,
                "uvIndex": 6,
                "visibility": 10,
                "ozone": 265.76
            },
            {
                "time": 1551031200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0011,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 59.05,
                "apparentTemperature": 59.05,
                "dewPoint": 26.7,
                "humidity": 0.29,
                "pressure": 1028.11,
                "windSpeed": 10.91,
                "windGust": 15.67,
                "windBearing": 57,
                "cloudCover": 0,
                "uvIndex": 7,
                "visibility": 10,
                "ozone": 266.51
            },
            {
                "time": 1551034800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 61.91,
                "apparentTemperature": 61.91,
                "dewPoint": 27.66,
                "humidity": 0.27,
                "pressure": 1027.52,
                "windSpeed": 10.75,
                "windGust": 13.48,
                "windBearing": 63,
                "cloudCover": 0,
                "uvIndex": 8,
                "visibility": 10,
                "ozone": 266.85
            },
            {
                "time": 1551038400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 64.31,
                "apparentTemperature": 64.31,
                "dewPoint": 27.73,
                "humidity": 0.25,
                "pressure": 1026.6,
                "windSpeed": 10.53,
                "windGust": 12.24,
                "windBearing": 68,
                "cloudCover": 0,
                "uvIndex": 7,
                "visibility": 10,
                "ozone": 266.9
            },
            {
                "time": 1551042000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 65.7,
                "apparentTemperature": 65.7,
                "dewPoint": 28.11,
                "humidity": 0.24,
                "pressure": 1025.81,
                "windSpeed": 10.25,
                "windGust": 11.57,
                "windBearing": 73,
                "cloudCover": 0,
                "uvIndex": 5,
                "visibility": 10,
                "ozone": 266.79
            },
            {
                "time": 1551045600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 65.88,
                "apparentTemperature": 65.88,
                "dewPoint": 29.05,
                "humidity": 0.25,
                "pressure": 1025.25,
                "windSpeed": 9.88,
                "windGust": 11.5,
                "windBearing": 76,
                "cloudCover": 0.02,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 266.42
            },
            {
                "time": 1551049200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 65.63,
                "apparentTemperature": 65.63,
                "dewPoint": 30.36,
                "humidity": 0.27,
                "pressure": 1024.86,
                "windSpeed": 9.42,
                "windGust": 11.98,
                "windBearing": 78,
                "cloudCover": 0.05,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 265.92
            },
            {
                "time": 1551052800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 63.97,
                "apparentTemperature": 63.97,
                "dewPoint": 31.33,
                "humidity": 0.29,
                "pressure": 1024.78,
                "windSpeed": 8.96,
                "windGust": 12.66,
                "windBearing": 80,
                "cloudCover": 0.11,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 265.58
            },
            {
                "time": 1551056400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 62.05,
                "apparentTemperature": 62.05,
                "dewPoint": 31.78,
                "humidity": 0.32,
                "pressure": 1025.19,
                "windSpeed": 8.55,
                "windGust": 13.59,
                "windBearing": 78,
                "cloudCover": 0.26,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 265.54
            },
            {
                "time": 1551060000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 59.6,
                "apparentTemperature": 59.6,
                "dewPoint": 31.98,
                "humidity": 0.35,
                "pressure": 1025.86,
                "windSpeed": 8.14,
                "windGust": 14.72,
                "windBearing": 74,
                "cloudCover": 0.45,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 265.67
            },
            {
                "time": 1551063600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 57.62,
                "apparentTemperature": 57.62,
                "dewPoint": 32.12,
                "humidity": 0.38,
                "pressure": 1026.43,
                "windSpeed": 7.8,
                "windGust": 15.72,
                "windBearing": 73,
                "cloudCover": 0.55,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 265.7
            },
            {
                "time": 1551067200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 56.19,
                "apparentTemperature": 56.19,
                "dewPoint": 32.21,
                "humidity": 0.4,
                "pressure": 1026.65,
                "windSpeed": 7.61,
                "windGust": 16.56,
                "windBearing": 71,
                "cloudCover": 0.53,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 265.61
            },
            {
                "time": 1551070800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 54.78,
                "apparentTemperature": 54.78,
                "dewPoint": 32.24,
                "humidity": 0.42,
                "pressure": 1026.74,
                "windSpeed": 7.49,
                "windGust": 17.3,
                "windBearing": 71,
                "cloudCover": 0.44,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 265.4
            },
            {
                "time": 1551074400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 53.34,
                "apparentTemperature": 53.34,
                "dewPoint": 32.34,
                "humidity": 0.45,
                "pressure": 1026.73,
                "windSpeed": 7.38,
                "windGust": 17.81,
                "windBearing": 71,
                "cloudCover": 0.39,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 265.53
            },
            {
                "time": 1551078000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 52.15,
                "apparentTemperature": 52.15,
                "dewPoint": 32.53,
                "humidity": 0.47,
                "pressure": 1026.57,
                "windSpeed": 7.22,
                "windGust": 17.8,
                "windBearing": 68,
                "cloudCover": 0.44,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 266.24
            },
            {
                "time": 1551081600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 51.26,
                "apparentTemperature": 51.26,
                "dewPoint": 32.81,
                "humidity": 0.49,
                "pressure": 1026.27,
                "windSpeed": 7.07,
                "windGust": 17.49,
                "windBearing": 66,
                "cloudCover": 0.53,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 267.29
            },
            {
                "time": 1551085200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 50.54,
                "apparentTemperature": 50.54,
                "dewPoint": 33.06,
                "humidity": 0.51,
                "pressure": 1026.04,
                "windSpeed": 7.05,
                "windGust": 17.38,
                "windBearing": 65,
                "cloudCover": 0.61,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 268.09
            },
            {
                "time": 1551088800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 49.29,
                "apparentTemperature": 46.26,
                "dewPoint": 33.19,
                "humidity": 0.54,
                "pressure": 1025.93,
                "windSpeed": 7.16,
                "windGust": 17.72,
                "windBearing": 66,
                "cloudCover": 0.65,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 268.58
            },
            {
                "time": 1551092400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 48.03,
                "apparentTemperature": 44.63,
                "dewPoint": 33.28,
                "humidity": 0.56,
                "pressure": 1025.88,
                "windSpeed": 7.39,
                "windGust": 18.33,
                "windBearing": 68,
                "cloudCover": 0.7,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 268.69
            },
            {
                "time": 1551096000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 47.49,
                "apparentTemperature": 43.82,
                "dewPoint": 33.41,
                "humidity": 0.58,
                "pressure": 1025.98,
                "windSpeed": 7.76,
                "windGust": 19.02,
                "windBearing": 71,
                "cloudCover": 0.76,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 269.01
            },
            {
                "time": 1551099600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 47.89,
                "apparentTemperature": 44.06,
                "dewPoint": 33.46,
                "humidity": 0.57,
                "pressure": 1026.36,
                "windSpeed": 8.34,
                "windGust": 20.09,
                "windBearing": 75,
                "cloudCover": 0.81,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 269.59
            },
            {
                "time": 1551103200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 48.39,
                "apparentTemperature": 44.39,
                "dewPoint": 33.61,
                "humidity": 0.56,
                "pressure": 1026.9,
                "windSpeed": 9.04,
                "windGust": 21.26,
                "windBearing": 80,
                "cloudCover": 0.85,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 270.17
            },
            {
                "time": 1551106800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0002,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 49.64,
                "apparentTemperature": 45.72,
                "dewPoint": 34.49,
                "humidity": 0.56,
                "pressure": 1027.1,
                "windSpeed": 9.61,
                "windGust": 21.47,
                "windBearing": 86,
                "cloudCover": 0.88,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 270.51
            },
            {
                "time": 1551110400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 52.6,
                "apparentTemperature": 52.6,
                "dewPoint": 36.47,
                "humidity": 0.54,
                "pressure": 1026.9,
                "windSpeed": 9.93,
                "windGust": 19.92,
                "windBearing": 94,
                "cloudCover": 0.87,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 270.58
            },
            {
                "time": 1551114000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 56.88,
                "apparentTemperature": 56.88,
                "dewPoint": 39.03,
                "humidity": 0.51,
                "pressure": 1026.38,
                "windSpeed": 10.1,
                "windGust": 17.55,
                "windBearing": 105,
                "cloudCover": 0.86,
                "uvIndex": 4,
                "visibility": 10,
                "ozone": 270.41
            },
            {
                "time": 1551117600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 60.26,
                "apparentTemperature": 60.26,
                "dewPoint": 41.45,
                "humidity": 0.5,
                "pressure": 1025.62,
                "windSpeed": 10.25,
                "windGust": 15.81,
                "windBearing": 113,
                "cloudCover": 0.83,
                "uvIndex": 5,
                "visibility": 10,
                "ozone": 269.83
            },
            {
                "time": 1551121200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 63.07,
                "apparentTemperature": 63.07,
                "dewPoint": 43.61,
                "humidity": 0.49,
                "pressure": 1024.39,
                "windSpeed": 10.48,
                "windGust": 15.08,
                "windBearing": 119,
                "cloudCover": 0.78,
                "uvIndex": 5,
                "visibility": 10,
                "ozone": 268.43
            },
            {
                "time": 1551124800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 65.05,
                "apparentTemperature": 65.05,
                "dewPoint": 45.7,
                "humidity": 0.5,
                "pressure": 1022.85,
                "windSpeed": 10.71,
                "windGust": 14.82,
                "windBearing": 124,
                "cloudCover": 0.72,
                "uvIndex": 5,
                "visibility": 10,
                "ozone": 266.72
            },
            {
                "time": 1551128400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 66.34,
                "apparentTemperature": 66.34,
                "dewPoint": 47.42,
                "humidity": 0.51,
                "pressure": 1021.7,
                "windSpeed": 10.78,
                "windGust": 14.76,
                "windBearing": 128,
                "cloudCover": 0.68,
                "uvIndex": 4,
                "visibility": 10,
                "ozone": 265.01
            },
            {
                "time": 1551132000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 66.53,
                "apparentTemperature": 66.53,
                "dewPoint": 48.47,
                "humidity": 0.52,
                "pressure": 1021.2,
                "windSpeed": 10.58,
                "windGust": 14.77,
                "windBearing": 128,
                "cloudCover": 0.65,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 263.53
            },
            {
                "time": 1551135600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 66.28,
                "apparentTemperature": 66.28,
                "dewPoint": 49.1,
                "humidity": 0.54,
                "pressure": 1021.03,
                "windSpeed": 10.18,
                "windGust": 14.92,
                "windBearing": 125,
                "cloudCover": 0.64,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 262.14
            },
            {
                "time": 1551139200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 65.27,
                "apparentTemperature": 65.27,
                "dewPoint": 49.8,
                "humidity": 0.57,
                "pressure": 1021.06,
                "windSpeed": 9.82,
                "windGust": 15.44,
                "windBearing": 122,
                "cloudCover": 0.67,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 260.99
            },
            {
                "time": 1551142800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0004,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 64.12,
                "apparentTemperature": 64.12,
                "dewPoint": 50.78,
                "humidity": 0.62,
                "pressure": 1021.35,
                "windSpeed": 9.62,
                "windGust": 16.68,
                "windBearing": 118,
                "cloudCover": 0.76,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 259.87
            },
            {
                "time": 1551146400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0018,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperature": 62.71,
                "apparentTemperature": 62.71,
                "dewPoint": 51.84,
                "humidity": 0.68,
                "pressure": 1021.81,
                "windSpeed": 9.44,
                "windGust": 18.19,
                "windBearing": 113,
                "cloudCover": 0.89,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 258.97
            },
            {
                "time": 1551150000,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0036,
                "precipProbability": 0.07,
                "precipType": "rain",
                "temperature": 61.9,
                "apparentTemperature": 61.9,
                "dewPoint": 52.82,
                "humidity": 0.72,
                "pressure": 1022.16,
                "windSpeed": 9.18,
                "windGust": 18.9,
                "windBearing": 109,
                "cloudCover": 0.99,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 258.2
            },
            {
                "time": 1551153600,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0056,
                "precipProbability": 0.14,
                "precipType": "rain",
                "temperature": 61.29,
                "apparentTemperature": 61.29,
                "dewPoint": 53.7,
                "humidity": 0.76,
                "pressure": 1022.41,
                "windSpeed": 8.87,
                "windGust": 18.33,
                "windBearing": 107,
                "cloudCover": 0.99,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 257.71
            },
            {
                "time": 1551157200,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0105,
                "precipProbability": 0.2,
                "precipType": "rain",
                "temperature": 60.53,
                "apparentTemperature": 60.53,
                "dewPoint": 54.47,
                "humidity": 0.8,
                "pressure": 1022.54,
                "windSpeed": 8.58,
                "windGust": 17.04,
                "windBearing": 107,
                "cloudCover": 0.97,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 257.36
            }
        ]
    },
    "daily": {
        "summary": "Light rain on Tuesday and Thursday, with high temperatures rising to 82°F on Friday.",
        "icon": "rain",
        "data": [
            {
                "time": 1550901600,
                "summary": "Mostly cloudy in the morning.",
                "icon": "partly-cloudy-night",
                "sunriseTime": 1550927226,
                "sunsetTime": 1550968226,
                "moonPhase": 0.65,
                "precipIntensity": 0.0007,
                "precipIntensityMax": 0.0062,
                "precipIntensityMaxTime": 1550912400,
                "precipProbability": 0.58,
                "precipType": "rain",
                "temperatureHigh": 76.33,
                "temperatureHighTime": 1550959200,
                "temperatureLow": 44.92,
                "temperatureLowTime": 1551013200,
                "apparentTemperatureHigh": 76.33,
                "apparentTemperatureHighTime": 1550959200,
                "apparentTemperatureLow": 40.13,
                "apparentTemperatureLowTime": 1551013200,
                "dewPoint": 40.66,
                "humidity": 0.52,
                "pressure": 1012.92,
                "windSpeed": 5.76,
                "windGust": 27.67,
                "windGustTime": 1550934000,
                "windBearing": 320,
                "cloudCover": 0.41,
                "uvIndex": 7,
                "uvIndexTime": 1550944800,
                "visibility": 7.4,
                "ozone": 261.67,
                "temperatureMin": 57.21,
                "temperatureMinTime": 1550901600,
                "temperatureMax": 76.33,
                "temperatureMaxTime": 1550959200,
                "apparentTemperatureMin": 57.21,
                "apparentTemperatureMinTime": 1550901600,
                "apparentTemperatureMax": 76.33,
                "apparentTemperatureMaxTime": 1550959200
            },
            {
                "time": 1550988000,
                "summary": "Partly cloudy starting in the evening.",
                "icon": "partly-cloudy-night",
                "sunriseTime": 1551013566,
                "sunsetTime": 1551054669,
                "moonPhase": 0.69,
                "precipIntensity": 0.0005,
                "precipIntensityMax": 0.0018,
                "precipIntensityMaxTime": 1550995200,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperatureHigh": 65.88,
                "temperatureHighTime": 1551045600,
                "temperatureLow": 47.49,
                "temperatureLowTime": 1551096000,
                "apparentTemperatureHigh": 65.88,
                "apparentTemperatureHighTime": 1551045600,
                "apparentTemperatureLow": 43.82,
                "apparentTemperatureLowTime": 1551096000,
                "dewPoint": 27.9,
                "humidity": 0.35,
                "pressure": 1025.46,
                "windSpeed": 8.15,
                "windGust": 26.56,
                "windGustTime": 1551020400,
                "windBearing": 46,
                "cloudCover": 0.12,
                "uvIndex": 8,
                "uvIndexTime": 1551034800,
                "visibility": 10,
                "ozone": 265.34,
                "temperatureMin": 44.92,
                "temperatureMinTime": 1551013200,
                "temperatureMax": 65.88,
                "temperatureMaxTime": 1551045600,
                "apparentTemperatureMin": 40.13,
                "apparentTemperatureMinTime": 1551013200,
                "apparentTemperatureMax": 65.88,
                "apparentTemperatureMaxTime": 1551045600
            },
            {
                "time": 1551074400,
                "summary": "Mostly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1551099905,
                "sunsetTime": 1551141111,
                "moonPhase": 0.72,
                "precipIntensity": 0.001,
                "precipIntensityMax": 0.0105,
                "precipIntensityMaxTime": 1551157200,
                "precipProbability": 0.2,
                "precipType": "rain",
                "temperatureHigh": 66.53,
                "temperatureHighTime": 1551132000,
                "temperatureLow": 57.2,
                "temperatureLowTime": 1551189600,
                "apparentTemperatureHigh": 66.53,
                "apparentTemperatureHighTime": 1551132000,
                "apparentTemperatureLow": 57.2,
                "apparentTemperatureLowTime": 1551189600,
                "dewPoint": 41.53,
                "humidity": 0.56,
                "pressure": 1024.38,
                "windSpeed": 8.34,
                "windGust": 21.47,
                "windGustTime": 1551106800,
                "windBearing": 100,
                "cloudCover": 0.75,
                "uvIndex": 5,
                "uvIndexTime": 1551117600,
                "visibility": 10,
                "ozone": 265.56,
                "temperatureMin": 47.49,
                "temperatureMinTime": 1551096000,
                "temperatureMax": 66.53,
                "temperatureMaxTime": 1551132000,
                "apparentTemperatureMin": 43.82,
                "apparentTemperatureMinTime": 1551096000,
                "apparentTemperatureMax": 66.53,
                "apparentTemperatureMaxTime": 1551132000
            },
            {
                "time": 1551160800,
                "summary": "Mostly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1551186244,
                "sunsetTime": 1551227553,
                "moonPhase": 0.76,
                "precipIntensity": 0.0093,
                "precipIntensityMax": 0.0275,
                "precipIntensityMaxTime": 1551182400,
                "precipProbability": 0.59,
                "precipType": "rain",
                "temperatureHigh": 72.08,
                "temperatureHighTime": 1551225600,
                "temperatureLow": 63.2,
                "temperatureLowTime": 1551276000,
                "apparentTemperatureHigh": 72.22,
                "apparentTemperatureHighTime": 1551225600,
                "apparentTemperatureLow": 63.64,
                "apparentTemperatureLowTime": 1551276000,
                "dewPoint": 57.97,
                "humidity": 0.83,
                "pressure": 1019.71,
                "windSpeed": 5.74,
                "windGust": 15.53,
                "windGustTime": 1551160800,
                "windBearing": 85,
                "cloudCover": 0.86,
                "uvIndex": 5,
                "uvIndexTime": 1551207600,
                "visibility": 9.78,
                "ozone": 257.11,
                "temperatureMin": 57.2,
                "temperatureMinTime": 1551189600,
                "temperatureMax": 72.08,
                "temperatureMaxTime": 1551225600,
                "apparentTemperatureMin": 57.2,
                "apparentTemperatureMinTime": 1551189600,
                "apparentTemperatureMax": 72.22,
                "apparentTemperatureMaxTime": 1551225600
            },
            {
                "time": 1551247200,
                "summary": "Mostly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1551272581,
                "sunsetTime": 1551313994,
                "moonPhase": 0.79,
                "precipIntensity": 0.0007,
                "precipIntensityMax": 0.0023,
                "precipIntensityMaxTime": 1551247200,
                "precipProbability": 0.13,
                "precipType": "rain",
                "temperatureHigh": 78.61,
                "temperatureHighTime": 1551308400,
                "temperatureLow": 65.04,
                "temperatureLowTime": 1551362400,
                "apparentTemperatureHigh": 78.73,
                "apparentTemperatureHighTime": 1551308400,
                "apparentTemperatureLow": 65.09,
                "apparentTemperatureLowTime": 1551362400,
                "dewPoint": 61.56,
                "humidity": 0.78,
                "pressure": 1017.46,
                "windSpeed": 4.51,
                "windGust": 14.08,
                "windGustTime": 1551322800,
                "windBearing": 145,
                "cloudCover": 0.87,
                "uvIndex": 5,
                "uvIndexTime": 1551290400,
                "visibility": 8.32,
                "ozone": 248.31,
                "temperatureMin": 63.2,
                "temperatureMinTime": 1551276000,
                "temperatureMax": 78.61,
                "temperatureMaxTime": 1551308400,
                "apparentTemperatureMin": 63.64,
                "apparentTemperatureMinTime": 1551276000,
                "apparentTemperatureMax": 78.73,
                "apparentTemperatureMaxTime": 1551308400
            },
            {
                "time": 1551333600,
                "summary": "Mostly cloudy until afternoon.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1551358918,
                "sunsetTime": 1551400435,
                "moonPhase": 0.82,
                "precipIntensity": 0.0039,
                "precipIntensityMax": 0.034,
                "precipIntensityMaxTime": 1551398400,
                "precipProbability": 0.19,
                "precipType": "rain",
                "temperatureHigh": 77.75,
                "temperatureHighTime": 1551387600,
                "temperatureLow": 64.61,
                "temperatureLowTime": 1551448800,
                "apparentTemperatureHigh": 77.84,
                "apparentTemperatureHighTime": 1551387600,
                "apparentTemperatureLow": 65.13,
                "apparentTemperatureLowTime": 1551448800,
                "dewPoint": 60.92,
                "humidity": 0.75,
                "pressure": 1014.6,
                "windSpeed": 5.35,
                "windGust": 17.7,
                "windGustTime": 1551409200,
                "windBearing": 92,
                "cloudCover": 0.54,
                "uvIndex": 7,
                "uvIndexTime": 1551380400,
                "visibility": 9.7,
                "ozone": 248.24,
                "temperatureMin": 64.87,
                "temperatureMinTime": 1551366000,
                "temperatureMax": 77.75,
                "temperatureMaxTime": 1551387600,
                "apparentTemperatureMin": 64.87,
                "apparentTemperatureMinTime": 1551366000,
                "apparentTemperatureMax": 77.84,
                "apparentTemperatureMaxTime": 1551387600
            },
            {
                "time": 1551420000,
                "summary": "Mostly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1551445254,
                "sunsetTime": 1551486875,
                "moonPhase": 0.85,
                "precipIntensity": 0.0005,
                "precipIntensityMax": 0.0023,
                "precipIntensityMaxTime": 1551441600,
                "precipProbability": 0.08,
                "precipType": "rain",
                "temperatureHigh": 82.03,
                "temperatureHighTime": 1551481200,
                "temperatureLow": 57,
                "temperatureLowTime": 1551535200,
                "apparentTemperatureHigh": 83.93,
                "apparentTemperatureHighTime": 1551481200,
                "apparentTemperatureLow": 57,
                "apparentTemperatureLowTime": 1551535200,
                "dewPoint": 63.23,
                "humidity": 0.77,
                "pressure": 1010.92,
                "windSpeed": 4.19,
                "windGust": 15,
                "windGustTime": 1551420000,
                "windBearing": 174,
                "cloudCover": 0.65,
                "uvIndex": 6,
                "uvIndexTime": 1551466800,
                "visibility": 10,
                "ozone": 241.31,
                "temperatureMin": 64.61,
                "temperatureMinTime": 1551448800,
                "temperatureMax": 82.03,
                "temperatureMaxTime": 1551481200,
                "apparentTemperatureMin": 65.13,
                "apparentTemperatureMinTime": 1551448800,
                "apparentTemperatureMax": 83.93,
                "apparentTemperatureMaxTime": 1551481200
            },
            {
                "time": 1551506400,
                "summary": "Mostly cloudy throughout the day and breezy until afternoon.",
                "icon": "wind",
                "sunriseTime": 1551531589,
                "sunsetTime": 1551573315,
                "moonPhase": 0.88,
                "precipIntensity": 0.0029,
                "precipIntensityMax": 0.0162,
                "precipIntensityMaxTime": 1551538800,
                "precipProbability": 0.12,
                "precipType": "rain",
                "temperatureHigh": 64.17,
                "temperatureHighTime": 1551556800,
                "temperatureLow": 47.69,
                "temperatureLowTime": 1551621600,
                "apparentTemperatureHigh": 64.17,
                "apparentTemperatureHighTime": 1551556800,
                "apparentTemperatureLow": 42.66,
                "apparentTemperatureLowTime": 1551621600,
                "dewPoint": 42.25,
                "humidity": 0.52,
                "pressure": 1019.09,
                "windSpeed": 12.16,
                "windGust": 41.5,
                "windGustTime": 1551531600,
                "windBearing": 40,
                "cloudCover": 0.71,
                "uvIndex": 7,
                "uvIndexTime": 1551549600,
                "visibility": 10,
                "ozone": 234,
                "temperatureMin": 54.03,
                "temperatureMinTime": 1551589200,
                "temperatureMax": 70.33,
                "temperatureMaxTime": 1551506400,
                "apparentTemperatureMin": 54.03,
                "apparentTemperatureMinTime": 1551589200,
                "apparentTemperatureMax": 71.1,
                "apparentTemperatureMaxTime": 1551506400
            }
        ]
    },
    "flags": {
        "sources": [
            "nearest-precip",
            "nwspa",
            "cmc",
            "gfs",
            "hrrr",
            "icon",
            "isd",
            "madis",
            "nam",
            "sref",
            "darksky"
        ],
        "nearest-station": 0.951,
        "units": "us"
    },
    "offset": -6
};
